routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::group(['middleware' => 'guest'], function(){
  Route::get('/', 'PostController@index')->name('index');
  Route::get('show/{post}', 'PostController@show')->name('blog.show');
  Route::get('category/{category}', 'PostController@category')->name('category');
  Route::get('admin/login', 'Backend\AdminController@createLogin')->name('login');
  Route::post('admin/login', 'Backend\AdminController@login');
});
Route::group(['middleware' => 'auth'], function(){
  Route::get('admin', 'Backend\AdminPostController@index')->name('admin.index');
  Route::get('admin/show/{post}', 'Backend\AdminPostController@show')->name('admin.show');
  Route::get('admin/post/create', 'Backend\AdminPostController@create')->name('admin.post.create');
  Route::post('admin/post/create', 'Backend\AdminPostController@store');
  Route::get('admin/category/create', 'Backend\AdminPostController@createCategory')->name('admin.category.create');
  Route::post('admin/category/create', 'Backend\AdminPostController@storeCategory');
  Route::get('logout', 'Backend\AdminController@logout')->name('logout');
});

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{

    protected $guarded = [];

    public function posts()
    {
      return $this->hasMany(Post::class);
    }

    public function getRouteKeyName()
    {
      return 'slug';
    }
}

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use GrahamCampbell\Markdown\Facades\Markdown;

class Post extends Model
{

    protected $guarded = [];

    public function getImageUrlAttribute($value)
    {
      $imageUrl = "";
      if( ! is_null($this->image)):
        $imagePath = public_path() . "/img/uploads/posts/". $this->image;
        if(file_exists($imagePath)) $imageUrl = asset("img/uploads/posts/". $this->image);
      endif;

      return $imageUrl;
    }

    public function author()
    {
      return $this->belongsTo(User::class);
    }

    public function getDateAttribute($value)
    {
      return $this->created_at->diffForHumans();
    }

    public function getBodyHtmlAttribute($value)
    {
      return $this->body ? Markdown::convertToHtml($this->body) : NULL;
    }

    public function getExcerptHtmlAttribute($value)
    {
      return $this->excerpt ? Markdown::convertToHtml($this->excerpt) : NULL;
    }

    public function category()
    {
      return $this->belongsTo(Category::class);
    }

    public function getSlugAttribute()
    {
      return str_replace(" ","-",$this->title);
    }


}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function posts()
    {
      return $this->hasMany(Post::class);
    }
}

app/Http/Controllers/Backend/AdminController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class AdminController extends Controller
{

    public function createLogin()
    {
      return view('blog.show-login');
    }

    public function login()
    {

      $this->validate(request(), [
        'email' => 'required',
        'password' => 'required'
      ]);

      if(!auth()->attempt(request(['email', 'password']))):
        return redirect()->back();
      endif;

      return redirect()->route('admin.index');
    }

    public function logout()
    {
      auth()->logout();
      return redirect()->route('index');
    }
}

app/Http/Controllers/Backend/AdminPostController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Post;
use App\Category;
use Image;

class AdminPostController extends Controller
{

  protected $limit = 4;

  public function index()
  {
    $posts = Post::with('author')->latest()->simplePaginate($this->limit);
    return view('backend.index', compact('posts'));
  }

  public function show(Post $post)
  {
    return view('backend.show', compact('post'));
  }

  public function category()
  {

  }

  public function create()
  {
    $categories = Category::with('posts')->orderBy('title', 'asc')->get();
    return view('backend.create',compact('categories'));
  }

  public function store()
  {
    $this->validate(request(), [
      'title' => 'required|min:5',
      'excerpt' => 'required|min:20',
      'body' => 'required|min:50'

    ]);

    if(request()->hasFile('image')):
      $image = request()->file('image');
      $filename = time() . "." . $image->getClientOriginalExtension();
      Image::make($image)->resize(750, 425)->save(public_path('img/uploads/posts/' . $filename));

      Post::create([
        'title' => request('title'),
        'slug' => str_replace(" ","-",strtolower(request('title'))),
        'category_id' => request('category'),
        'excerpt' => request('excerpt'),
        'body' => request('body'),
        'author_id' => 1,
        'image' => $filename
      ]);

    else:
      Post::create([
        'title' => request('title'),
        'slug' => str_replace(" ","-",strtolower(request('title'))),
        'category_id' => request('category'),
        'excerpt' => request('excerpt'),
        'body' => request('body'),
        'author_id' => 1
      ]);

    endif;

    return redirect()->route('admin.index');
  }

  public function createCategory()
  {
    return view('backend.create-category');
  }

  public function storeCategory()
  {
    $this->validate(request(), [
      'title' => 'required',
      'slug' => 'required|alpha_dash'
    ]);

    Category::create([
      'title' => request('title'),
      'slug' => request('slug'),
    ]);
    return redirect()->route('admin.index');
  }

}

app/Http/Controllers/Backend/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Post;
use App\Category;

class PostController extends Controller
{

    protected $limit = 4;

    public function index()
    {

      
      $posts = Post::with('author')->latest()->simplePaginate($this->limit);
      $categories = Category::with('posts')->orderBy('title', 'asc')->get();
      return view('blog.index', compact('posts', 'categories'));
    }


    public function show(Post $post)
    {
      $categories = Category::with('posts')->orderBy('title', 'asc')->get();
      return view('blog.show', compact('post', 'categories'));
    }

    public function category(Category $category)
    {

      $categoryName = $category->title;
      $posts = $category->posts()->with('author')->latest()->simplePaginate($this->limit);
      $categories = Category::with('posts')->orderBy('title', 'asc')->get();
      return view('blog.index', compact('posts', 'categories', 'categoryName'));
    }
}

resources/views/backend/create-category.blade.php
@extends('layouts.backend.master')

@section('main')
    <div class="row admn-frm">
      <form class="form-horizontal" method="post" action="{{ route('admin.category.create')}}">
        {{csrf_field()}}
          <div class="form-group required">
              <label for="name">title</label>
              <input type="text" name="title" id="name" class="form-control">
          </div>
          <div class="form-group">
              <label for="slug">Slug</label>
              <input type="text" name="slug" id="slug" class="form-control">
          </div>
          <div class="clearfix">
              <div class="pull-left">
                  <button type="submit" class="btn btn-lg btn-success">Submit</button>
              </div>
              <div class="pull-right">
                  <p class="text-muted">
                      <span class="required">*</span>
                      <em>Indicates required fields</em>
                  </p>
              </div>
          </div>
      </form>
    </div>
@endsection

resources/views/backend/create.blade.php
@extends('layouts.backend.master')

@section('main')
    <div class="row admn-frm">
      <form class="form-horizontal" enctype="multipart/form-data" method="post" action="{{ route('admin.post.create')}}">
        {{csrf_field()}}
          <div class="form-group required">
              <label for="name">title</label>
              <input type="text" name="title" id="name" class="form-control">
          </div>
          <div class="form-group required">
              <label for="name">Category</label>
              <select class="form-control" name="category">
                @foreach($categories as $category)
                  <option value="{{$category->id}}">{{$category->title}}</option>
                @endforeach
              </select>
          </div>
          <div class="form-group">
              <label for="image">Upload Image</label>
              <input type="file" name="image" id="image" class="form-control">
          </div>
          <div class="form-group required">
              <label for="excerpt">Excerpt</label>
              <textarea name="excerpt" id="excerpt" rows="4" class="form-control"></textarea>
          </div>
          <div class="form-group required">
              <label for="body">Body</label>
              <textarea name="body" id="body" rows="15" class="form-control"></textarea>
          </div>
          <div class="clearfix">
              <div class="pull-left">
                  <button type="submit" class="btn btn-lg btn-success">Submit</button>
              </div>
              <div class="pull-right">
                  <p class="text-muted">
                      <span class="required">*</span>
                      <em>Indicates required fields</em>
                  </p>
              </div>
          </div>
      </form>
    </div>
@endsection

resources/views/backend/index.blade.php
@extends('layouts.backend.master')

@section('main')
    @if( ! $posts->count())
      <div class="alert alert-info">
        <p>Nothing Found</p>
      </div>
    @else
        @if( isset($categoryName))
          <div class="alert alert-info">
            <p>Category: <strong>{{ $categoryName}}</strong></p>
          </div>
        @endif

        @foreach($posts as $post)
          <article class="post-item">
            @if($post->image_url)
                <div class="post-item-image">
                    <a href="{{ route('admin.show', $post->slug)}}">
                        <img src="{{ $post->image_url}}" class="img-responsive" alt="">
                    </a>
                </div>
              @endif
              <div class="post-item-body">
                  <div class="padding-10">
                      <h2><a href="{{ route('admin.show', $post->slug)}}">{{ $post->title }}</a></h2>
                      <p>{!! $post->excerpt_html !!}</p>
                  </div>

                  <div class="post-meta padding-10 clearfix">
                      <div class="pull-left">
                          <ul class="post-meta-group">
                              <li><i class="fa fa-user"></i><a href="#"> {{ $post->author->name}}</a></li>
                              <li><i class="fa fa-clock-o"></i><time> {{ $post->date}}</time></li>
                              <li><i class="fa fa-folder"></i><a href="{{ route('category', $post->category->slug)}}"> {{$post->category->title}}</a></li>
                              <li><i class="fa fa-comments"></i><a href="#">4 Comments</a></li>

                          </ul>
                      </div>
                      <div class="pull-right">
                          <a href="{{ route('admin.show', $post->slug)}}">Continue Reading &raquo;</a>
                      </div>
                  </div>
              </div>
          </article>
        @endforeach

    @endif

    <nav>
    {{ $posts->links()}}
    </nav>
@endsection

resources/views/backend/show.blade.php
@extends('layouts.backend.master')

@section('main')
<article class="post-item post-detail">
    @if($post->image_url)
      <div class="post-item-image">
          <img src="{{ $post->image_url}}" alt="">
      </div>
    @endif

    <div class="post-item-body">
        <div class="padding-10">
            <h1>{{ $post->title}}</h1>

            <div class="post-meta no-border">
                <ul class="post-meta-group">
                    <li><i class="fa fa-user"></i><a href="#"> {{ $post->author->name}}</a></li>
                    <li><i class="fa fa-clock-o"></i><time> {{ $post->date}}</time></li>
                    <li><i class="fa fa-tags"></i><a href="#"> Blog</a></li>
                    <li><i class="fa fa-comments"></i><a href="#">4 Comments</a></li>
                </ul>
            </div>

            {!! $post->body_html !!}

        </div>
    </div>
</article>

<article class="post-author padding-10">
    <div class="media">
      <div class="media-left">
        <a href="#">
          <img alt="Author 1" src="/img/author.jpg" class="media-object">
        </a>
      </div>
      <div class="media-body">
        <h4 class="media-heading"><a href="#">Masaru Edo</a></h4>
        <div class="post-author-count">
          <a href="#">
              <i class="fa fa-clone"></i>
              90 posts
          </a>
        </div>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nobis ad aut sunt cum, mollitia excepturi neque sint magnam minus aliquam, voluptatem, labore quis praesentium eum quae dolorum temporibus consequuntur! Non.</p>
      </div>
    </div>
</article>

<article class="post-comments">
    <h3><i class="fa fa-comments"></i> 5 Comments</h3>

    <div class="comment-body padding-10">
        <ul class="comments-list">
            <li class="comment-item">
                <div class="comment-heading clearfix">
                    <div class="comment-author-meta">
                        <h4>John Doe <small>January 14, 2016</small></h4>
                    </div>
                </div>
                <div class="comment-content">
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Optio nesciunt nulla est, atque ratione nostrum cumque ducimus maxime, amet enim tempore ipsam. Id ea, veniam ipsam perspiciatis assumenda magnam doloribus!</p>
                    <p>Quibusdam iusto culpa, necessitatibus, libero sequi quae commodi ea ab non facilis enim vitae inventore laborum hic unde esse debitis. Adipisci nostrum reprehenderit explicabo, non molestias aliquid quibusdam tempore. Vel.</p>
                </div>
            </li>

            <li class="comment-item">
                <div class="comment-heading clearfix">
                    <div class="comment-author-meta">
                        <h4>John Doe <small>January 14, 2016</small></h4>
                    </div>
                </div>
                <div class="comment-content">
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Optio nesciunt nulla est, atque ratione nostrum cumque ducimus maxime, amet enim tempore ipsam. Id ea, veniam ipsam perspiciatis assumenda magnam doloribus!</p>
                    <p>Quibusdam iusto culpa, necessitatibus, libero sequi quae commodi ea ab non facilis enim vitae inventore laborum hic unde esse debitis. Adipisci nostrum reprehenderit explicabo, non molestias aliquid quibusdam tempore. Vel.</p>

                    <ul class="comments-list-children">
                        <li class="comment-item">
                            <div class="comment-heading clearfix">
                                <div class="comment-author-meta">
                                    <h4>John Doe <small>January 14, 2016</small></h4>
                                </div>
                            </div>
                            <div class="comment-content">
                                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Optio nesciunt nulla est, atque ratione nostrum cumque ducimus maxime, amet enim tempore ipsam. Id ea, veniam ipsam perspiciatis assumenda magnam doloribus!</p>
                                <p>Quibusdam iusto culpa, necessitatibus, libero sequi quae commodi ea ab non facilis enim vitae inventore laborum hic unde esse debitis. Adipisci nostrum reprehenderit explicabo, non molestias aliquid quibusdam tempore. Vel.</p>
                            </div>
                        </li>

                        <li class="comment-item">
                            <div class="comment-heading clearfix">
                                <div class="comment-author-meta">
                                    <h4>John Doe <small>January 14, 2016</small></h4>
                                </div>
                            </div>
                            <div class="comment-content">
                                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Optio nesciunt nulla est, atque ratione nostrum cumque ducimus maxime, amet enim tempore ipsam. Id ea, veniam ipsam perspiciatis assumenda magnam doloribus!</p>
                                <p>Quibusdam iusto culpa, necessitatibus, libero sequi quae commodi ea ab non facilis enim vitae inventore laborum hic unde esse debitis. Adipisci nostrum reprehenderit explicabo, non molestias aliquid quibusdam tempore. Vel.</p>

                                <ul class="comments-list-children">
                                    <li class="comment-item">
                                        <div class="comment-heading clearfix">
                                            <div class="comment-author-meta">
                                                <h4>John Doe <small>January 14, 2016</small></h4>
                                            </div>
                                        </div>
                                        <div class="comment-content">
                                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Optio nesciunt nulla est, atque ratione nostrum cumque ducimus maxime, amet enim tempore ipsam. Id ea, veniam ipsam perspiciatis assumenda magnam doloribus!</p>
                                            <p>Quibusdam iusto culpa, necessitatibus, libero sequi quae commodi ea ab non facilis enim vitae inventore laborum hic unde esse debitis. Adipisci nostrum reprehenderit explicabo, non molestias aliquid quibusdam tempore. Vel.</p>
                                        </div>
                                    </li>
                                </ul>
                            </div>
                        </li>
                    </ul>
                </div>
            </li>
        </ul>

    </div>

    <div class="comment-footer padding-10">
        <h3>Leave a comment</h3>
        <form>
            <div class="form-group required">
                <label for="name">Name</label>
                <input type="text" name="name" id="name" class="form-control">
            </div>
            <div class="form-group required">
                <label for="email">Email</label>
                <input type="text" name="email" id="email" class="form-control">
            </div>
            <div class="form-group">
                <label for="website">Website</label>
                <input type="text" name="website" id="website" class="form-control">
            </div>
            <div class="form-group required">
                <label for="comment">Comment</label>
                <textarea name="comment" id="comment" rows="6" class="form-control"></textarea>
            </div>
            <div class="clearfix">
                <div class="pull-left">
                    <button type="submit" class="btn btn-lg btn-success">Submit</button>
                </div>
                <div class="pull-right">
                    <p class="text-muted">
                        <span class="required">*</span>
                        <em>Indicates required fields</em>
                    </p>
                </div>
            </div>
        </form>
    </div>

</article>
@endsection

resources/views/blog/index.blade.php
@extends('layouts.master')

@section('main')

  @if( ! $posts->count())
    <div class="alert alert-info">
      <p>Nothing Found</p>
    </div>
  @else
      @if( isset($categoryName))
        <div class="alert alert-info">
          <p>Category: <strong>{{ $categoryName}}</strong></p>
        </div>
      @endif

      @foreach($posts as $post)
        <article class="post-item">
          @if($post->image_url)
              <div class="post-item-image">
                  <a href="{{ route('blog.show', $post->slug)}}">
                      <img src="{{ $post->image_url}}" alt="">
                  </a>
              </div>
            @endif
            <div class="post-item-body">
                <div class="padding-10">
                    <h2><a href="{{ route('blog.show', $post->slug)}}">{{ $post->title }}</a></h2>
                    <p>{!! $post->excerpt_html !!}</p>
                </div>

                <div class="post-meta padding-10 clearfix">
                    <div class="pull-left">
                        <ul class="post-meta-group">
                            <li><i class="fa fa-user"></i><a href="#"> {{ $post->author->name}}</a></li>
                            <li><i class="fa fa-clock-o"></i><time> {{ $post->date}}</time></li>
                            <li><i class="fa fa-folder"></i><a href="{{ route('category', $post->category->slug)}}"> {{$post->category->title}}</a></li>
                            <li><i class="fa fa-comments"></i><a href="#">4 Comments</a></li>
                        </ul>
                    </div>
                    <div class="pull-right">
                        <a href="{{ route('blog.show', $post->slug)}}">Continue Reading &raquo;</a>
                    </div>
                </div>
            </div>
        </article>
      @endforeach

  @endif

<nav>
  {{ $posts->links()}}
</nav>
@endsection

@section('sidebar')
  @include('blog.sidebar');
@endsection

resources/views/blog/show.blade.php
@extends('layouts.master')

@section('main')
<article class="post-item post-detail">
    @if($post->image_url)
      <div class="post-item-image">
          <img src="{{ $post->image_url}}" alt="">
      </div>
    @endif

    <div class="post-item-body">
        <div class="padding-10">
            <h1>{{ $post->title}}</h1>

            <div class="post-meta no-border">
                <ul class="post-meta-group">
                    <li><i class="fa fa-user"></i><a href="#"> {{ $post->author->name}}</a></li>
                    <li><i class="fa fa-clock-o"></i><time> {{ $post->date}}</time></li>
                    <li><i class="fa fa-tags"></i><a href="#"> Blog</a></li>
                    <li><i class="fa fa-comments"></i><a href="#">4 Comments</a></li>
                </ul>
            </div>

            {!! $post->body_html !!}

        </div>
    </div>
</article>

<article class="post-author padding-10">
    <div class="media">
      <div class="media-left">
        <a href="#">
          <img alt="Author 1" src="/img/author.jpg" class="media-object">
        </a>
      </div>
      <div class="media-body">
        <h4 class="media-heading"><a href="#">Masaru Edo</a></h4>
        <div class="post-author-count">
          <a href="#">
              <i class="fa fa-clone"></i>
              90 posts
          </a>
        </div>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nobis ad aut sunt cum, mollitia excepturi neque sint magnam minus aliquam, voluptatem, labore quis praesentium eum quae dolorum temporibus consequuntur! Non.</p>
      </div>
    </div>
</article>

<article class="post-comments">
    <h3><i class="fa fa-comments"></i> 5 Comments</h3>

    <div class="comment-body padding-10">
        <ul class="comments-list">
            <li class="comment-item">
                <div class="comment-heading clearfix">
                    <div class="comment-author-meta">
                        <h4>John Doe <small>January 14, 2016</small></h4>
                    </div>
                </div>
                <div class="comment-content">
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Optio nesciunt nulla est, atque ratione nostrum cumque ducimus maxime, amet enim tempore ipsam. Id ea, veniam ipsam perspiciatis assumenda magnam doloribus!</p>
                    <p>Quibusdam iusto culpa, necessitatibus, libero sequi quae commodi ea ab non facilis enim vitae inventore laborum hic unde esse debitis. Adipisci nostrum reprehenderit explicabo, non molestias aliquid quibusdam tempore. Vel.</p>
                </div>
            </li>

            <li class="comment-item">
                <div class="comment-heading clearfix">
                    <div class="comment-author-meta">
                        <h4>John Doe <small>January 14, 2016</small></h4>
                    </div>
                </div>
                <div class="comment-content">
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Optio nesciunt nulla est, atque ratione nostrum cumque ducimus maxime, amet enim tempore ipsam. Id ea, veniam ipsam perspiciatis assumenda magnam doloribus!</p>
                    <p>Quibusdam iusto culpa, necessitatibus, libero sequi quae commodi ea ab non facilis enim vitae inventore laborum hic unde esse debitis. Adipisci nostrum reprehenderit explicabo, non molestias aliquid quibusdam tempore. Vel.</p>

                    <ul class="comments-list-children">
                        <li class="comment-item">
                            <div class="comment-heading clearfix">
                                <div class="comment-author-meta">
                                    <h4>John Doe <small>January 14, 2016</small></h4>
                                </div>
                            </div>
                            <div class="comment-content">
                                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Optio nesciunt nulla est, atque ratione nostrum cumque ducimus maxime, amet enim tempore ipsam. Id ea, veniam ipsam perspiciatis assumenda magnam doloribus!</p>
                                <p>Quibusdam iusto culpa, necessitatibus, libero sequi quae commodi ea ab non facilis enim vitae inventore laborum hic unde esse debitis. Adipisci nostrum reprehenderit explicabo, non molestias aliquid quibusdam tempore. Vel.</p>
                            </div>
                        </li>

                        <li class="comment-item">
                            <div class="comment-heading clearfix">
                                <div class="comment-author-meta">
                                    <h4>John Doe <small>January 14, 2016</small></h4>
                                </div>
                            </div>
                            <div class="comment-content">
                                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Optio nesciunt nulla est, atque ratione nostrum cumque ducimus maxime, amet enim tempore ipsam. Id ea, veniam ipsam perspiciatis assumenda magnam doloribus!</p>
                                <p>Quibusdam iusto culpa, necessitatibus, libero sequi quae commodi ea ab non facilis enim vitae inventore laborum hic unde esse debitis. Adipisci nostrum reprehenderit explicabo, non molestias aliquid quibusdam tempore. Vel.</p>

                                <ul class="comments-list-children">
                                    <li class="comment-item">
                                        <div class="comment-heading clearfix">
                                            <div class="comment-author-meta">
                                                <h4>John Doe <small>January 14, 2016</small></h4>
                                            </div>
                                        </div>
                                        <div class="comment-content">
                                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Optio nesciunt nulla est, atque ratione nostrum cumque ducimus maxime, amet enim tempore ipsam. Id ea, veniam ipsam perspiciatis assumenda magnam doloribus!</p>
                                            <p>Quibusdam iusto culpa, necessitatibus, libero sequi quae commodi ea ab non facilis enim vitae inventore laborum hic unde esse debitis. Adipisci nostrum reprehenderit explicabo, non molestias aliquid quibusdam tempore. Vel.</p>
                                        </div>
                                    </li>
                                </ul>
                            </div>
                        </li>
                    </ul>
                </div>
            </li>
        </ul>

    </div>

    <div class="comment-footer padding-10">
        <h3>Leave a comment</h3>
        <form>
            <div class="form-group required">
                <label for="name">Name</label>
                <input type="text" name="name" id="name" class="form-control">
            </div>
            <div class="form-group required">
                <label for="email">Email</label>
                <input type="text" name="email" id="email" class="form-control">
            </div>
            <div class="form-group">
                <label for="website">Website</label>
                <input type="text" name="website" id="website" class="form-control">
            </div>
            <div class="form-group required">
                <label for="comment">Comment</label>
                <textarea name="comment" id="comment" rows="6" class="form-control"></textarea>
            </div>
            <div class="clearfix">
                <div class="pull-left">
                    <button type="submit" class="btn btn-lg btn-success">Submit</button>
                </div>
                <div class="pull-right">
                    <p class="text-muted">
                        <span class="required">*</span>
                        <em>Indicates required fields</em>
                    </p>
                </div>
            </div>
        </form>
    </div>

</article>
@endsection

@section('sidebar')
  @include('blog.sidebar');
@endsection